name: PR Checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SwiftLint
        run: brew install swiftlint
        
      - name: Run SwiftLint
        run: swiftlint

  test:
    name: Run Tests
    needs: lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Tests
        run: |
          xcodebuild test \
            -scheme YourScheme \
            -destination 'platform=iOS Simulator,OS=latest'
