name: SwiftLint Check

on: [push, pull_request]

jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint
