name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

#list of jobs to perform
jobs:
  #the only job in the list, named `build`
  build: 
    #specify OS to run the jobs on
    runs-on: macos-latest 
    #sequential steps to run for the `build` job
    steps: 
      # step 1, use Marketplace action called Checkout@v2, to checkout the code
    - uses: actions/checkout@v2 #'uses' keyword launches the Marketplace action
      # step 2, verbosely build the package using the `swift` CLI
    - name: Build
      run: swift build -v #'run' keyword executes the command, as if it's run in terminal
      # step 3, verbosely test the package using the `swift` CLI
    - name: Run tests
      run: swift test -v #'run' keyword executes the command, as if it's run in terminal

