name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'

    - name: Run Tests
      run: |
        xcodebuild test \
          -project Coco.xcodeproj \
          -scheme CocoTests \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4'


